### ISSUE TITLE
Add a loading icon to the SearchView

### ISSUE THREAD

**Issue by doppie** [doppie/SaxionRoosters#18]
When a user is waiting for their autocomplete search results we want a loading icon to be shown on the right(instead of the X button).

**Comment by doppie** [comment]
Requested an issue at the lib from @lapism/SearchView

**Comment by lapism** [comment]
I will do it ASAP :)

**Comment by doppie** [comment]
Sure thing mate, thanks :)

**Comment by lapism** [comment]
Already added :-P.
