### ISSUE TITLE
Update the model

### ISSUE THREAD

**Issue by doppie** [doppie/SaxionRoosters#3]
The parser currently only parses a few basic things while much more useful info can be parsed.

Refactor the model and make it more complete.

For example: 
span class="datacell_left">
        a href="/schedule/teacher:EDU01/week:0">E.F. Duipmans          
/span>

Right now we only parse the name "E.F. Duipmans" while it would be interesting to make the Teacher model more complete by adding its abbreviation or even the URL.

**Comment by ruudgreven** [comment]
I think using the iCal files is easier and less error prone. They have changed the HTML a lot over the years. They also have an API, but last time I checked that it wasn't stable. You can checkout my iCal parser at: https://github.com/ruudgreven/roosterious/blob/master/scripts/weekly/S6ReadClassSchedules.php

**Comment by doppie** [comment]
Hi Ruud, thanks for the input, we are thinking about writing an external library api to handle custom parsers & caching of data in a sqlite db. This way we can also easily create and test an iCal parser. 

Pros for iCal:
- less requests(think we can get all weeks in one request?).
- less error prone due to steady format.

Cons for iCal:
- less data available (no links to bison, teachers etc.)
- description contains multiple data types  (teachers, college type)
