### ISSUE TITLE
Maak gebruik van API

### ISSUE THREAD

**Issue by BenjaminFaal** [doppie/SaxionRoosters#38]
Ik zag jullie app in de play store en heb uiteindelijk deze repo gevonden.

Het ziet er naar uit dat jullie de HTML roosters ophalen en parsen. Dit kan veel sneller met de API. Ik gebruikte die ook voor mijn app.

Zie http://api.roosters.saxion.nl

Succes!

**Comment by doppie** [comment]
Daar wees Saxion ons ook op, maar ze weten niet voor hoelang die er nog is. We willen de API wel nog gaan implementeren, feel free om daar je bijdrage aan te leveren in de vorm van een pull request!

**Comment by ruudgreven** [comment]
De garantie dat de HTML hetzelfde blijft heb je ook niet. Ik heb destijds de iCal gebruikt, dat kan ook nog...
Ik begreep overigens dat het uberhaupt nog niet duidelijk is of de roosters publiek op internet zichtbaar blijven.

**Comment by doppie** [comment]
Goed punt, daar zijn we ons ook bewust van. Om die reden willen we zowel de API als de HTMLParser geïmplementeerd hebben, op die manier kunnen we terugvallen op de HTMLParser als de API bijvoorbeeld niet naar behoren werkt. De HTML kan natuurlijk aangepast worden maar ik verwacht hoogstens veldaanpassingen, dat zou slechts betekenen dat informatie kan veranderen maar de HTMLParser zal blijven werken (in most cases). Eigenlijk zouden we tests moeten schrijven voor de parser. 


Saxion gaf ook aan over te willen stappen naar oAuth maar wist niet wanneer en of hoe, als dat het geval wordt zal een inlog procedure toegevoegd moeten worden.

In die zin is het jammer dat alles zo onzeker en onduidelijk is in de toekomst. Ik denk dat op dat vlak veel verbeterd kan worden.
