### ISSUE TITLE
Scroll to current day when a schedule is loaded.

### ISSUE THREAD

**Issue by doppie** [doppie/SaxionRoosters#40]

**Comment by niels-io** [comment]
I use this to navigate to the current day, I unfortunaly do not have time to implement it into this repository.
        Calendar c = Calendar.getInstance();
        int currentDay = c.get(Calendar.DAY_OF_WEEK);
        Boolean notifications = prefs.getBoolean("Notificaties", false);
            switch (currentDay) {
                case 1:viewPager.setCurrentItem(0, true);break;
                case 2:viewPager.setCurrentItem(0, true);break;
                case 3:viewPager.setCurrentItem(1, true);break;
                case 4:viewPager.setCurrentItem(2, true);break;
                case 5:viewPager.setCurrentItem(3, true);break;
                case 6:viewPager.setCurrentItem(4, true);break;
                case 7:viewPager.setCurrentItem(0, true);break;
                default:viewPager.setCurrentItem(0, true);break;
            }


I hope it's useful, I can implent it if I have time, but it will take long.
