### ISSUE TITLE
Statusbar kleur en navigatiebar kleur

### ISSUE THREAD

**Issue by developingwild** [doppie/SaxionRoosters#41]
De statusbar kleur matcht niet met de basis kleur. Tevens zou ik graag de keuze willen zien in het instellingen scherm om een andere kleur voor de app te kiezen. Ik zou ook graag een gekleurde navigatiebar kleur willen zien.

**Comment by doppie** [comment]
Thanks voor je feedback. We hebben bewust gekozen voor deze kleuren, niet persé omdat het "mooi" is, meer omdat het herkenbaar is voor mensen van het Saxion. Op dit moment is het zo dat we niet de naam "Saxion" in de app titel mogen zetten en daarom moeten we op andere manieren herkenningspunten genereren.

Het is een leuke extra feature, maar functioneel gezien voegt het (voor nu) weinig toe. Voel je vrij om deze feature te bouwen, dan zal hij toegevoegd worden aan de app.
