### ISSUE TITLE
Show details for a College

### ISSUE THREAD

**Issue by doppie** [doppie/SaxionRoosters#5]
We need a detail dialog or activity for details of a college. 
This could include: 
- Teacher(s)
- Location(s)
- Time of college
- College description
- Optional cool features such as: 
   * Sharing to mail, Whatsapp, Calendar(iCal)
   * Showing a map of the Saxion(well this is a very big feature, but it could be nice.)

**Comment by HugoOlthof** [comment]
Made a start with this issue:

- Teachers are shown
- Locations are shown
- Time is shown
