### ISSUE TITLE
Chrash whilst performing a search-task in the main activity

### ISSUE THREAD

**Issue by wesselperik** [doppie/SaxionRoosters#68]
When i'm searching for a teacher schedule, the app crashes after I have typed in 3 characters. Stacktrace:

`11-29 18:37:52.998 32165-32253/dev.saxionroosters E/SaxionRoosters: Request: http://roosters.saxion.nl/?q=Ro`
`11-29 18:37:53.788 32165-32165/dev.saxionroosters E/debug: updateUI`
`11-29 18:37:55.823 32165-32214/dev.saxionroosters E/SaxionRoosters: Request: http://roosters.saxion.nl/?q=Rog`
`11-29 18:37:56.158 32165-32165/dev.saxionroosters E/debug: updateUI`
`11-29 18:37:56.183 32165-32165/dev.saxionroosters E/AndroidRuntime: FATAL EXCEPTION: main`
`                                                                    Process: dev.saxionroosters, PID: 32165`
`                                                                    java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true`
`                                                                        at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5425)`
`                                                                        at android.support.v7.widget.RecyclerView$Recycler.recycleView(RecyclerView.java:5369)`
`                                                                        at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleViewAt(RecyclerView.java:7715)`
`                                                                        at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleAllViews(RecyclerView.java:8988)`
`                                                                        at android.support.v7.widget.RecyclerView.setAdapterInternal(RecyclerView.java:987)`
`                                                                        at android.support.v7.widget.RecyclerView.setAdapter(RecyclerView.java:958)`
`                                                                        at com.lapism.searchview.SearchView.setAdapter(SearchView.java:635)`
`                                                                        at dev.saxionroosters.activities.MainActivity.updateUI(MainActivity.java:203)`
`                                                                        at dev.saxionroosters.activities.MainActivity_.access$001(MainActivity_.java:31)`
`                                                                        at dev.saxionroosters.activities.MainActivity_$1$1.run(MainActivity_.java:113)`
`                                                                        at android.os.Handler.handleCallback(Handler.java:739)`
`                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)`
`                                                                        at android.os.Looper.loop(Looper.java:152)`
`                                                                        at android.app.ActivityThread.main(ActivityThread.java:5507)`
`                                                                        at java.lang.reflect.Method.invoke(Native Method)`
`                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)`
`                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by doppie** [comment]
Dit is een bug die ik zelf ook tegenkwam bij het testen afgelopen weekend. Is ontstaan bij de versie upgrade van de SearchView library. Ik had er al een simpele oplossing voor maar nog niet gepushed. Voor zover ik weet is dit niet live.
