### ISSUE TITLE
Show the last shown result when the app is restarted

### ISSUE THREAD

**Issue by doppie** [doppie/SaxionRoosters#9]
When a user starts the app, we want it to show the last result.

**Comment by HugoOlthof** [comment]
Wouldn't it be more useful to load the default class/teacher which will be chosen when a user starts the app for the first time? #13

**Comment by doppie** [comment]
Agreed. Will create an issue with a "settings" menu, for any settings after the first initialisation.

**Comment by doppie** [comment]
closed #9
